sever:
    port: 8443
    sslPort: 8080
    undertow:
      worker-threads: 20
      buffer-size: 512
      io-threads: 2
spring:
    datasource:
        name: sakila
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.99.100:3306/sakila
          username: root
          password: 123456

          initial-size: 1
          min-idle: 1
          max-active: 20

          max-wait: 60000

          time-between-eviction-runs-millis: 60000

          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false

          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    logging:
        file:   logs/my.log
        config: classpath:logback.xml
        level:
            org.springframework.web: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hand.exam1.model



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


mapper:
  mappers: com.hand.exam1.utils.CommonMapper
  not-empty: false
  identity: MYSQL




